PilotD2Redo:
    datadir: /oak/stanford/groups/pritch/users/emma/data/GWT/PilotD2Redo/
    sample_metadata: /oak/stanford/groups/pritch/users/emma/data/GWT/sample_metadata/GWT_sample_metadata.PilotD2Redo.csv

PilotD2Redo_Lane2:
    datadir: /oak/stanford/groups/pritch/users/emma/data/GWT/PilotD2Redo_Lane2/
    sample_metadata: /oak/stanford/groups/pritch/users/emma/data/GWT/sample_metadata/GWT_sample_metadata.PilotD2Redo_Lane2.csv

Pilot:
    datadir: /oak/stanford/groups/pritch/users/emma/data/GWT/TcellsGW_pilot/
    sample_metadata: 

