name: gwt-env
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.11
  - pip:
    - scanpy
    - rapids-singlecell
    - jupyter
    - git+https://github.com/scverse/anndata.git
    # - anndata>=0.12
    - genomic_features
    - ibis-framework==8.0.0
    - scipy
    - openpyxl
    - mudata
    - scvi
    # - git+https://github.com/emdann/perturbseq-tools.git@main