name: gwt-env
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.11
  - pip:
    - scanpy
    - genomic_features
    - ibis-framework==8.0.0
    - scipy
    - crispat
    - openpyxl
    - git+https://github.com/emdann/perturbseq-tools.git@main